# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a536bd0dcbbcf13f78893b7d122903f4c099c4cbe0960703a0cacdbb86ee9823811a99290df76ab1dc91995ac092778d7a4bb12cf4cfcaa95a9734d9e0937b1e

test:
  secret_key_base: f635363e01f5e6190a0c54697f6325b9a03d5566a2afd5c0cd148e0cc4008ac270cba38de322257afe0b9356138b41d00d99eaeed28df44ba02800d8a87822fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
